openapi: 3.0.0
info:
  title: Laravel API
  description: Dokumentacja API aplikacji stworzonej w Laravel
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Lokalny serwer deweloperski

paths:
  /user:
    get:
      summary: Pobierz dane zalogowanego użytkownika
      security:
        - sanctumAuth: []
      responses:
        '200':
          description: Dane użytkownika
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /register:
    post:
      summary: Zarejestruj użytkownika
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        '201':
          description: Użytkownik zarejestrowany

  /login:
    post:
      summary: Zaloguj użytkownika
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: Zalogowano użytkownika

  /userprofile:
    get:
      summary: Pobierz profil użytkownika
      security:
        - sanctumAuth: []
      responses:
        '200':
          description: Profil użytkownika
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /logout:
    post:
      summary: Wyloguj użytkownika
      security:
        - sanctumAuth: []
      responses:
        '204':
          description: Wylogowano użytkownika

  /brands:
    get:
      summary: Pobierz listę marek
      responses:
        '200':
          description: Lista marek
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
    post:
      summary: Dodaj nową markę
      security:
        - sanctumAuth: []
        - adminAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrandInput'
      responses:
        '201':
          description: Marka dodana

  /brands/{id}:
    get:
      summary: Pobierz szczegóły marki
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Szczegóły marki
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brand'
    put:
      summary: Zaktualizuj markę
      security:
        - sanctumAuth: []
        - adminAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrandInput'
      responses:
        '200':
          description: Marka zaktualizowana
    delete:
      summary: Usuń markę
      security:
        - sanctumAuth: []
        - adminAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Marka usunięta

  /fuel-price-suggestions:
    get:
      summary: Pobierz sugestie cen paliw
      security:
        - sanctumAuth: []
      responses:
        '200':
          description: Sugestie cen paliw
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FuelPriceSuggestion'
    post:
      summary: Dodaj nową sugestię ceny paliwa
      security:
        - sanctumAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FuelPriceSuggestionInput'
      responses:
        '201':
          description: Sugestia ceny paliwa dodana

  /fuel-types:
    get:
      summary: Pobierz typy paliw
      responses:
        '200':
          description: Lista typów paliw
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FuelType'
    post:
      summary: Dodaj nowy typ paliwa
      security:
        - sanctumAuth: []
        - adminAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FuelTypeInput'
      responses:
        '201':
          description: Typ paliwa dodany

  /stations:
    get:
      summary: Pobierz listę stacji
      responses:
        '200':
          description: Lista stacji
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Station'
    post:
      summary: Dodaj nową stację
      security:
        - sanctumAuth: []
        - adminAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StationInput'
      responses:
        '201':
          description: Stacja dodana

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
    RegisterUser:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    LoginUser:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    Brand:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    BrandInput:
      type: object
      properties:
        name:
          type: string
    FuelType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    FuelTypeInput:
      type: object
      properties:
        name:
          type: string
    FuelPriceSuggestion:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        price:
          type: number
    FuelPriceSuggestionInput:
      type: object
      properties:
        price:
          type: number
    Station:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        address:
          type: string
    StationInput:
      type: object
      properties:
        name:
          type: string
        address:
          type: string

securitySchemes:
  sanctumAuth:
    type: http
    scheme: bearer
  adminAuth:
    type: http
    scheme: bearer
